export type EngineDef = {
  slug: string;
  name: string;
  tagline: string;
  emoji: string;
  color: string; // gradient stop 1
  color2: string; // gradient stop 2
  status: "live" | "soon";
  category:
    | "Classics"
    | "Groups"
    | "Numbers"
    | "Play"
    | "Everyday"
    | "Random";
};

export const ENGINES: EngineDef[] = [
  {
    slug: "coin",
    name: "Coin Toss",
    tagline: "The timeless 50/50.",
    emoji: "🪙",
    color: "#facc15",
    color2: "#f59e0b",
    status: "live",
    category: "Classics",
  },
  {
    slug: "dice",
    name: "Dice",
    tagline: "D4 to D20. Roll like a wizard.",
    emoji: "🎲",
    color: "#f472b6",
    color2: "#a855f7",
    status: "live",
    category: "Classics",
  },
  {
    slug: "wheel",
    name: "Spin Wheel",
    tagline: "Infinite entries. Weighted. Beautiful.",
    emoji: "🎡",
    color: "#38bdf8",
    color2: "#6366f1",
    status: "live",
    category: "Classics",
  },
  {
    slug: "bottle",
    name: "Bottle Spin",
    tagline: "Physics-based. Whoever it points to.",
    emoji: "🍾",
    color: "#22c55e",
    color2: "#14b8a6",
    status: "live",
    category: "Groups",
  },
  {
    slug: "person",
    name: "Person Chooser",
    tagline: "Radial picker for 2–100 people.",
    emoji: "🧑‍🤝‍🧑",
    color: "#8b5cf6",
    color2: "#ec4899",
    status: "live",
    category: "Groups",
  },
  {
    slug: "name",
    name: "Name Picker",
    tagline: "Import a list. Pick a winner.",
    emoji: "🎯",
    color: "#f97316",
    color2: "#ef4444",
    status: "live",
    category: "Groups",
  },
  {
    slug: "yesno",
    name: "Yes / No",
    tagline: "The universe's answer, revealed.",
    emoji: "✨",
    color: "#a78bfa",
    color2: "#f0abfc",
    status: "live",
    category: "Everyday",
  },
  {
    slug: "magic8",
    name: "Magic 8 Ball",
    tagline: "Ask. Shake. Behold.",
    emoji: "🎱",
    color: "#0ea5e9",
    color2: "#1e3a8a",
    status: "live",
    category: "Everyday",
  },
  {
    slug: "number",
    name: "Random Number",
    tagline: "From min to max, with drama.",
    emoji: "🔢",
    color: "#10b981",
    color2: "#0ea5e9",
    status: "live",
    category: "Numbers",
  },
  {
    slug: "color",
    name: "Random Color",
    tagline: "Hex. RGB. Gradient. Inspiration.",
    emoji: "🎨",
    color: "#ec4899",
    color2: "#facc15",
    status: "live",
    category: "Play",
  },
  {
    slug: "emoji",
    name: "Random Emoji",
    tagline: "A little joy on demand.",
    emoji: "😀",
    color: "#fbbf24",
    color2: "#f472b6",
    status: "live",
    category: "Play",
  },
  {
    slug: "letter",
    name: "Random Letter",
    tagline: "A to Z. Or your alphabet.",
    emoji: "🔤",
    color: "#f43f5e",
    color2: "#8b5cf6",
    status: "live",
    category: "Numbers",
  },
  {
    slug: "direction",
    name: "Direction Spinner",
    tagline: "North, south, east, west.",
    emoji: "🧭",
    color: "#22d3ee",
    color2: "#3b82f6",
    status: "live",
    category: "Play",
  },
  {
    slug: "rps",
    name: "Rock Paper Scissors",
    tagline: "Best of one against fate.",
    emoji: "✊",
    color: "#f43f5e",
    color2: "#f59e0b",
    status: "live",
    category: "Play",
  },
  {
    slug: "card",
    name: "Card Picker",
    tagline: "From a 52-card deck.",
    emoji: "🂡",
    color: "#e2e8f0",
    color2: "#94a3b8",
    status: "live",
    category: "Classics",
  },
  {
    slug: "team",
    name: "Team Generator",
    tagline: "Split people fairly.",
    emoji: "👥",
    color: "#06b6d4",
    color2: "#8b5cf6",
    status: "live",
    category: "Groups",
  },
  {
    slug: "pair",
    name: "Pair Generator",
    tagline: "Pair everyone up. No repeats.",
    emoji: "💞",
    color: "#f472b6",
    color2: "#f97316",
    status: "live",
    category: "Groups",
  },
  {
    slug: "fortune",
    name: "Fortune Cookie",
    tagline: "Crack. Read. Believe.",
    emoji: "🥠",
    color: "#fbbf24",
    color2: "#ef4444",
    status: "live",
    category: "Everyday",
  },
  {
    slug: "finger",
    name: "Finger Chooser",
    tagline: "Everyone taps. One is chosen.",
    emoji: "👆",
    color: "#f472b6",
    color2: "#22d3ee",
    status: "live",
    category: "Groups",
  },
  {
    slug: "timer",
    name: "Random Timer",
    tagline: "A surprise countdown.",
    emoji: "⏱",
    color: "#22c55e",
    color2: "#eab308",
    status: "live",
    category: "Random",
  },
  {
    slug: "truthdare",
    name: "Truth or Dare",
    tagline: "The classic party trap.",
    emoji: "🎭",
    color: "#8b5cf6",
    color2: "#ec4899",
    status: "live",
    category: "Play",
  },
  {
    slug: "task",
    name: "Task Selector",
    tagline: "Randomize the to-do.",
    emoji: "✅",
    color: "#22c55e",
    color2: "#0ea5e9",
    status: "live",
    category: "Everyday",
  },
  {
    slug: "prize",
    name: "Prize Picker",
    tagline: "Draw the lucky one.",
    emoji: "🎁",
    color: "#f43f5e",
    color2: "#f59e0b",
    status: "live",
    category: "Random",
  },
  {
    slug: "tree",
    name: "Decision Tree",
    tagline: "Yes/no branches, animated.",
    emoji: "🌳",
    color: "#10b981",
    color2: "#84cc16",
    status: "live",
    category: "Everyday",
  },
  {
    slug: "object",
    name: "Object Chooser",
    tagline: "Anything, from anywhere.",
    emoji: "📦",
    color: "#94a3b8",
    color2: "#e2e8f0",
    status: "live",
    category: "Random",
  },
  {
    slug: "flipbook",
    name: "Flip Book",
    tagline: "Flip through possibilities.",
    emoji: "📖",
    color: "#f97316",
    color2: "#f472b6",
    status: "live",
    category: "Play",
  },
];

export function findEngine(slug: string) {
  return ENGINES.find((e) => e.slug === slug);
}
